// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgwhtqtuouvwybnagriw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnd2h0cXR1b3V2d3libmFncml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MTMyMTMsImV4cCI6MjA2MTQ4OTIxM30.tRz5WKeXS8GxvUO0ylH9GsnDOkGFc0eGHyWxEmCZVz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);